name: Daily Weather Line Notification

on:
  workflow_dispatch:
  schedule:
    - cron: '05 21 * * *'  # 鬧鐘 1：台灣 05:05
    - cron: '25 21 * * *'  # 鬧鐘 2：台灣 05:25
    - cron: '45 21 * * *'  # 鬧鐘 3：台灣 05:45

jobs:
  run-weather-script:
    runs-on: ubuntu-latest
    steps:
      - name: 檢查程式碼
        uses: actions/checkout@v5

      - name: 設定 Python 環境
        uses: actions/setup-python@v6
        with:
          python-version: '3.10'

      - name: 安裝網路請求套件
        run: pip install requests urllib3

      - name: 執行天氣通知
        env:
          LINE_ACCESS_TOKEN: ${{ secrets.WEATHER_LINE_TOKEN }}
        run: python main.py
